using System.Collections.Generic;
using System.IO;
using UnityEngine;

public static class FurnitureCatalog
{
    private static readonly List<FurnitureRecord> CatalogItems = new List<FurnitureRecord>
    {
        new FurnitureRecord("chair-01", "Lounge Chair", "Chairs"),
        new FurnitureRecord("chair-02", "Dining Chair", "Chairs"),
        new FurnitureRecord("sofa-01", "Soft Sofa", "Sofas"),
        new FurnitureRecord("sofa-02", "Sectional Sofa", "Sofas"),
        new FurnitureRecord("table-01", "Coffee Table", "Tables"),
        new FurnitureRecord("table-02", "Dining Table", "Tables"),
        new FurnitureRecord("bed-01", "Platform Bed", "Beds"),
        new FurnitureRecord("closet-01", "Wardrobe Closet", "Closets"),
        new FurnitureRecord("drawer-01", "Wooden Drawer", "Drawers"),
        new FurnitureRecord("kitchen-01", "Kitchen Cabinet", "Kitchen"),
        new FurnitureRecord("bath-01", "Bathroom Vanity", "Bathroom"),
        new FurnitureRecord("bathroom-bathroomvanity01", "Bathroom Vanity 01", "Bathroom"),
        new FurnitureRecord("bathroom-bathroomvanity02", "Bathroom Vanity 02", "Bathroom"),
        new FurnitureRecord("bathroom-bathroomvanity03", "Bathroom Vanity 03", "Bathroom"),
        new FurnitureRecord("bathroom-bathroomvanity04", "Bathroom Vanity 04", "Bathroom"),
        new FurnitureRecord("bathroom-bathroomvanity05", "Bathroom Vanity 05", "Bathroom"),
        new FurnitureRecord("bathroom-bathroomvanity06", "Bathroom Vanity 06", "Bathroom"),
        new FurnitureRecord("bathroom-bathroomvanity07", "Bathroom Vanity 07", "Bathroom"),
        new FurnitureRecord("bathroom-bathtub01", "Bath Tub 01", "Bathroom"),
        new FurnitureRecord("bathroom-bathtub02", "Bath Tub 02", "Bathroom"),
        new FurnitureRecord("bathroom-bathtub03", "Bath Tub 03", "Bathroom"),
        new FurnitureRecord("bathroom-bathtub04", "Bath Tub 04", "Bathroom"),
        new FurnitureRecord("bathroom-bathtub05", "Bath Tub 05", "Bathroom"),
        new FurnitureRecord("bathroom-bathtub06", "Bath Tub 06", "Bathroom"),
        new FurnitureRecord("bathroom-bathtub07", "Bath Tub 07", "Bathroom"),
        new FurnitureRecord("bathroom-showersystem01", "Shower System 01", "Bathroom"),
        new FurnitureRecord("bathroom-showersystem02", "Shower System 02", "Bathroom"),
        new FurnitureRecord("bathroom-showersystem03", "Shower System 03", "Bathroom"),
        new FurnitureRecord("bathroom-showersystem04", "Shower System 04", "Bathroom"),
        new FurnitureRecord("bathroom-showersystem05", "Shower System 05", "Bathroom"),
        new FurnitureRecord("bathroom-showersystem06", "Shower System 06", "Bathroom"),
        new FurnitureRecord("bathroom-showersystem07", "Shower System 07", "Bathroom"),
        new FurnitureRecord("bathroom-tissuehanger01", "Tissue Hanger 01", "Bathroom"),
        new FurnitureRecord("bathroom-tissuehanger02", "Tissue Hanger 02", "Bathroom"),
        new FurnitureRecord("bathroom-tissuehanger03", "Tissue Hanger 03", "Bathroom"),
        new FurnitureRecord("bathroom-tissuehanger04", "Tissue Hanger 04", "Bathroom"),
        new FurnitureRecord("bathroom-tissuehanger05", "Tissue Hanger 05", "Bathroom"),
        new FurnitureRecord("bathroom-tissuehanger06", "Tissue Hanger 06", "Bathroom"),
        new FurnitureRecord("bathroom-tissuehanger07", "Tissue Hanger 07", "Bathroom"),
        new FurnitureRecord("bathroom-toilet01", "Toilet 01", "Bathroom"),
        new FurnitureRecord("bathroom-toilet02", "Toilet 02", "Bathroom"),
        new FurnitureRecord("bathroom-toilet03", "Toilet 03", "Bathroom"),
        new FurnitureRecord("bathroom-toilet04", "Toilet 04", "Bathroom"),
        new FurnitureRecord("bathroom-toilet05", "Toilet 05", "Bathroom"),
        new FurnitureRecord("bathroom-toilet06", "Toilet 06", "Bathroom"),
        new FurnitureRecord("bathroom-toilet07", "Toilet 07", "Bathroom"),
        new FurnitureRecord("bathroom-towelhanger01", "Towel Hanger 01", "Bathroom"),
        new FurnitureRecord("bathroom-towelhanger02", "Towel Hanger 02", "Bathroom"),
        new FurnitureRecord("bathroom-towelhanger03", "Towel Hanger 03", "Bathroom"),
        new FurnitureRecord("bathroom-towelhanger04", "Towel Hanger 04", "Bathroom"),
        new FurnitureRecord("bathroom-towelhanger05", "Towel Hanger 05", "Bathroom"),
        new FurnitureRecord("bathroom-towelhanger06", "Towel Hanger 06", "Bathroom"),
        new FurnitureRecord("bathroom-towelhanger07", "Towel Hanger 07", "Bathroom"),
        new FurnitureRecord("bathroom-washbasin01", "Wash Basin 01", "Bathroom"),
        new FurnitureRecord("bathroom-washbasin02", "Wash Basin 02", "Bathroom"),
        new FurnitureRecord("bathroom-washbasin03", "Wash Basin 03", "Bathroom"),
        new FurnitureRecord("bathroom-washbasin04", "Wash Basin 04", "Bathroom"),
        new FurnitureRecord("bathroom-washbasin05", "Wash Basin 05", "Bathroom"),
        new FurnitureRecord("bathroom-washbasin06", "Wash Basin 06", "Bathroom"),
        new FurnitureRecord("bathroom-washbasin07", "Wash Basin 07", "Bathroom"),
        new FurnitureRecord("bed-bed01", "Bed 01", "Beds"),
        new FurnitureRecord("bed-bed02", "Bed 02", "Beds"),
        new FurnitureRecord("bed-bed03", "Bed 03", "Beds"),
        new FurnitureRecord("bed-bed04", "Bed 04", "Beds"),
        new FurnitureRecord("bed-bed05", "Bed 05", "Beds"),
        new FurnitureRecord("bed-bed06", "Bed 06", "Beds"),
        new FurnitureRecord("bed-bed07", "Bed 07", "Beds"),
        new FurnitureRecord("bed-bed08", "Bed 08", "Beds"),
        new FurnitureRecord("bed-bed09", "Bed 09", "Beds"),
        new FurnitureRecord("bed-bed10", "Bed 10", "Beds"),
        new FurnitureRecord("bed-bed11", "Bed 11", "Beds"),
        new FurnitureRecord("bed-bed12", "Bed 12", "Beds"),
        new FurnitureRecord("bed-bed13", "Bed 13", "Beds"),
        new FurnitureRecord("bed-bed14", "Bed 14", "Beds"),
        new FurnitureRecord("bed-bed15", "Bed 15", "Beds"),
        new FurnitureRecord("bed-bed16", "Bed 16", "Beds"),
        new FurnitureRecord("bed-bed17", "Bed 17", "Beds"),
        new FurnitureRecord("bed-bed18", "Bed 18", "Beds"),
        new FurnitureRecord("bed-bed19", "Bed 19", "Beds"),
        new FurnitureRecord("bed-bed20", "Bed 20", "Beds"),
        new FurnitureRecord("bed-bed21", "Bed 21", "Beds"),
        new FurnitureRecord("bed-bed22", "Bed 22", "Beds"),
        new FurnitureRecord("bed-bed23", "Bed 23", "Beds"),
        new FurnitureRecord("bed-bed24", "Bed 24", "Beds"),
        new FurnitureRecord("bed-bed25", "Bed 25", "Beds"),
        new FurnitureRecord("bed-bed26", "Bed 26", "Beds"),
        new FurnitureRecord("bed-bed27", "Bed 27", "Beds"),
        new FurnitureRecord("bed-bed28", "Bed 28", "Beds"),
        new FurnitureRecord("bed-bed29", "Bed 29", "Beds"),
        new FurnitureRecord("bed-bed30", "Bed 30", "Beds"),
        new FurnitureRecord("bed-bed31", "Bed 31", "Beds"),
        new FurnitureRecord("bed-bed32", "Bed 32", "Beds"),
        new FurnitureRecord("bed-bed33", "Bed 33", "Beds"),
        new FurnitureRecord("bed-bed34", "Bed 34", "Beds"),
        new FurnitureRecord("bed-bed35", "Bed 35", "Beds"),
        new FurnitureRecord("bed-bed36", "Bed 36", "Beds"),
        new FurnitureRecord("bed-bed37", "Bed 37", "Beds"),
        new FurnitureRecord("bed-bed38", "Bed 38", "Beds"),
        new FurnitureRecord("bed-bed39", "Bed 39", "Beds"),
        new FurnitureRecord("bed-bed40", "Bed 40", "Beds"),
        new FurnitureRecord("bed-bed41", "Bed 41", "Beds"),
        new FurnitureRecord("bed-bed42", "Bed 42", "Beds"),
        new FurnitureRecord("bed-bed43", "Bed 43", "Beds"),
        new FurnitureRecord("bed-bed44", "Bed 44", "Beds"),
        new FurnitureRecord("bed-bed45", "Bed 45", "Beds"),
        new FurnitureRecord("bed-bed46", "Bed 46", "Beds"),
        new FurnitureRecord("bed-bed47", "Bed 47", "Beds"),
        new FurnitureRecord("bed-bed48", "Bed 48", "Beds"),
        new FurnitureRecord("bed-bed49", "Bed 49", "Beds"),
        new FurnitureRecord("bed-bed50", "Bed 50", "Beds"),
        new FurnitureRecord("chair-chair01", "Chair 01", "Chairs"),
        new FurnitureRecord("chair-chair02", "Chair 02", "Chairs"),
        new FurnitureRecord("chair-chair03", "Chair 03", "Chairs"),
        new FurnitureRecord("chair-chair04", "Chair 04", "Chairs"),
        new FurnitureRecord("chair-chair05", "Chair 05", "Chairs"),
        new FurnitureRecord("chair-chair06", "Chair 06", "Chairs"),
        new FurnitureRecord("chair-chair07", "Chair 07", "Chairs"),
        new FurnitureRecord("chair-chair08", "Chair 08", "Chairs"),
        new FurnitureRecord("chair-chair09", "Chair 09", "Chairs"),
        new FurnitureRecord("chair-chair10", "Chair 10", "Chairs"),
        new FurnitureRecord("chair-chair11", "Chair 11", "Chairs"),
        new FurnitureRecord("chair-chair12", "Chair 12", "Chairs"),
        new FurnitureRecord("chair-chair13", "Chair 13", "Chairs"),
        new FurnitureRecord("chair-chair14", "Chair 14", "Chairs"),
        new FurnitureRecord("chair-chair15", "Chair 15", "Chairs"),
        new FurnitureRecord("chair-chair16", "Chair 16", "Chairs"),
        new FurnitureRecord("chair-chair17", "Chair 17", "Chairs"),
        new FurnitureRecord("chair-chair18", "Chair 18", "Chairs"),
        new FurnitureRecord("chair-chair19", "Chair 19", "Chairs"),
        new FurnitureRecord("chair-chair20", "Chair 20", "Chairs"),
        new FurnitureRecord("chair-chair21", "Chair 21", "Chairs"),
        new FurnitureRecord("chair-chair22", "Chair 22", "Chairs"),
        new FurnitureRecord("chair-chair23", "Chair 23", "Chairs"),
        new FurnitureRecord("chair-chair24", "Chair 24", "Chairs"),
        new FurnitureRecord("chair-chair25", "Chair 25", "Chairs"),
        new FurnitureRecord("chair-chair26", "Chair 26", "Chairs"),
        new FurnitureRecord("chair-chair27", "Chair 27", "Chairs"),
        new FurnitureRecord("chair-chair28", "Chair 28", "Chairs"),
        new FurnitureRecord("chair-chair29", "Chair 29", "Chairs"),
        new FurnitureRecord("chair-chair30", "Chair 30", "Chairs"),
        new FurnitureRecord("chair-chair31", "Chair 31", "Chairs"),
        new FurnitureRecord("chair-chair32", "Chair 32", "Chairs"),
        new FurnitureRecord("chair-chair33", "Chair 33", "Chairs"),
        new FurnitureRecord("chair-chair34", "Chair 34", "Chairs"),
        new FurnitureRecord("chair-chair35", "Chair 35", "Chairs"),
        new FurnitureRecord("chair-chair36", "Chair 36", "Chairs"),
        new FurnitureRecord("chair-chair37", "Chair 37", "Chairs"),
        new FurnitureRecord("chair-chair38", "Chair 38", "Chairs"),
        new FurnitureRecord("chair-chair39", "Chair 39", "Chairs"),
        new FurnitureRecord("chair-chair40", "Chair 40", "Chairs"),
        new FurnitureRecord("chair-chair41", "Chair 41", "Chairs"),
        new FurnitureRecord("chair-chair42", "Chair 42", "Chairs"),
        new FurnitureRecord("chair-chair43", "Chair 43", "Chairs"),
        new FurnitureRecord("chair-chair44", "Chair 44", "Chairs"),
        new FurnitureRecord("chair-chair45", "Chair 45", "Chairs"),
        new FurnitureRecord("chair-chair46", "Chair 46", "Chairs"),
        new FurnitureRecord("chair-chair47", "Chair 47", "Chairs"),
        new FurnitureRecord("chair-chair48", "Chair 48", "Chairs"),
        new FurnitureRecord("chair-chair49", "Chair 49", "Chairs"),
        new FurnitureRecord("chair-chair50", "Chair 50", "Chairs"),
        new FurnitureRecord("closet-closet01", "Closet 01", "Closets"),
        new FurnitureRecord("closet-closet02", "Closet 02", "Closets"),
        new FurnitureRecord("closet-closet03", "Closet 03", "Closets"),
        new FurnitureRecord("closet-closet04", "Closet 04", "Closets"),
        new FurnitureRecord("closet-closet05", "Closet 05", "Closets"),
        new FurnitureRecord("closet-closet06", "Closet 06", "Closets"),
        new FurnitureRecord("closet-closet07", "Closet 07", "Closets"),
        new FurnitureRecord("closet-closet08", "Closet 08", "Closets"),
        new FurnitureRecord("closet-closet09", "Closet 09", "Closets"),
        new FurnitureRecord("closet-closet10", "Closet 10", "Closets"),
        new FurnitureRecord("closet-closet11", "Closet 11", "Closets"),
        new FurnitureRecord("closet-closet12", "Closet 12", "Closets"),
        new FurnitureRecord("closet-closet13", "Closet 13", "Closets"),
        new FurnitureRecord("closet-closet14", "Closet 14", "Closets"),
        new FurnitureRecord("closet-closet15", "Closet 15", "Closets"),
        new FurnitureRecord("closet-closet16", "Closet 16", "Closets"),
        new FurnitureRecord("closet-closet17", "Closet 17", "Closets"),
        new FurnitureRecord("closet-closet18", "Closet 18", "Closets"),
        new FurnitureRecord("closet-closet19", "Closet 19", "Closets"),
        new FurnitureRecord("closet-closet20", "Closet 20", "Closets"),
        new FurnitureRecord("closet-closet21", "Closet 21", "Closets"),
        new FurnitureRecord("closet-closet22", "Closet 22", "Closets"),
        new FurnitureRecord("closet-closet23", "Closet 23", "Closets"),
        new FurnitureRecord("closet-closet24", "Closet 24", "Closets"),
        new FurnitureRecord("closet-closet25", "Closet 25", "Closets"),
        new FurnitureRecord("closet-closet26", "Closet 26", "Closets"),
        new FurnitureRecord("closet-closet27", "Closet 27", "Closets"),
        new FurnitureRecord("closet-closet28", "Closet 28", "Closets"),
        new FurnitureRecord("closet-closet29", "Closet 29", "Closets"),
        new FurnitureRecord("closet-closet30", "Closet 30", "Closets"),
        new FurnitureRecord("closet-closet31", "Closet 31", "Closets"),
        new FurnitureRecord("closet-closet32", "Closet 32", "Closets"),
        new FurnitureRecord("closet-closet33", "Closet 33", "Closets"),
        new FurnitureRecord("closet-closet34", "Closet 34", "Closets"),
        new FurnitureRecord("closet-closet35", "Closet 35", "Closets"),
        new FurnitureRecord("closet-closet36", "Closet 36", "Closets"),
        new FurnitureRecord("closet-closet37", "Closet 37", "Closets"),
        new FurnitureRecord("closet-closet38", "Closet 38", "Closets"),
        new FurnitureRecord("closet-closet39", "Closet 39", "Closets"),
        new FurnitureRecord("closet-closet40", "Closet 40", "Closets"),
        new FurnitureRecord("closet-closet41", "Closet 41", "Closets"),
        new FurnitureRecord("closet-closet42", "Closet 42", "Closets"),
        new FurnitureRecord("closet-closet43", "Closet 43", "Closets"),
        new FurnitureRecord("closet-closet44", "Closet 44", "Closets"),
        new FurnitureRecord("closet-closet45", "Closet 45", "Closets"),
        new FurnitureRecord("closet-closet46", "Closet 46", "Closets"),
        new FurnitureRecord("closet-closet47", "Closet 47", "Closets"),
        new FurnitureRecord("closet-closet48", "Closet 48", "Closets"),
        new FurnitureRecord("closet-closet49", "Closet 49", "Closets"),
        new FurnitureRecord("closet-closet50", "Closet 50", "Closets"),
        new FurnitureRecord("cushion-cushion01", "Cushion 01", "Cushions"),
        new FurnitureRecord("cushion-cushion02", "Cushion 02", "Cushions"),
        new FurnitureRecord("cushion-cushion03", "Cushion 03", "Cushions"),
        new FurnitureRecord("cushion-cushion04", "Cushion 04", "Cushions"),
        new FurnitureRecord("cushion-cushion05", "Cushion 05", "Cushions"),
        new FurnitureRecord("cushion-cushion06", "Cushion 06", "Cushions"),
        new FurnitureRecord("cushion-cushion07", "Cushion 07", "Cushions"),
        new FurnitureRecord("cushion-cushion08", "Cushion 08", "Cushions"),
        new FurnitureRecord("cushion-cushion09", "Cushion 09", "Cushions"),
        new FurnitureRecord("cushion-cushion10", "Cushion 10", "Cushions"),
        new FurnitureRecord("cushion-cushion11", "Cushion 11", "Cushions"),
        new FurnitureRecord("cushion-cushion12", "Cushion 12", "Cushions"),
        new FurnitureRecord("cushion-cushion13", "Cushion 13", "Cushions"),
        new FurnitureRecord("cushion-cushion14", "Cushion 14", "Cushions"),
        new FurnitureRecord("cushion-cushion15", "Cushion 15", "Cushions"),
        new FurnitureRecord("cushion-cushion16", "Cushion 16", "Cushions"),
        new FurnitureRecord("cushion-cushion17", "Cushion 17", "Cushions"),
        new FurnitureRecord("cushion-cushion18", "Cushion 18", "Cushions"),
        new FurnitureRecord("cushion-cushion19", "Cushion 19", "Cushions"),
        new FurnitureRecord("cushion-cushion20", "Cushion 20", "Cushions"),
        new FurnitureRecord("cushion-cushion21", "Cushion 21", "Cushions"),
        new FurnitureRecord("cushion-cushion22", "Cushion 22", "Cushions"),
        new FurnitureRecord("cushion-cushion23", "Cushion 23", "Cushions"),
        new FurnitureRecord("cushion-cushion24", "Cushion 24", "Cushions"),
        new FurnitureRecord("cushion-cushion25", "Cushion 25", "Cushions"),
        new FurnitureRecord("cushion-cushion26", "Cushion 26", "Cushions"),
        new FurnitureRecord("cushion-cushion27", "Cushion 27", "Cushions"),
        new FurnitureRecord("cushion-cushion28", "Cushion 28", "Cushions"),
        new FurnitureRecord("cushion-cushion29", "Cushion 29", "Cushions"),
        new FurnitureRecord("cushion-cushion30", "Cushion 30", "Cushions"),
        new FurnitureRecord("cushion-cushion31", "Cushion 31", "Cushions"),
        new FurnitureRecord("cushion-cushion32", "Cushion 32", "Cushions"),
        new FurnitureRecord("cushion-cushion33", "Cushion 33", "Cushions"),
        new FurnitureRecord("cushion-cushion34", "Cushion 34", "Cushions"),
        new FurnitureRecord("cushion-cushion35", "Cushion 35", "Cushions"),
        new FurnitureRecord("cushion-cushion36", "Cushion 36", "Cushions"),
        new FurnitureRecord("cushion-cushion37", "Cushion 37", "Cushions"),
        new FurnitureRecord("cushion-cushion38", "Cushion 38", "Cushions"),
        new FurnitureRecord("cushion-cushion39", "Cushion 39", "Cushions"),
        new FurnitureRecord("cushion-cushion40", "Cushion 40", "Cushions"),
        new FurnitureRecord("cushion-cushion41", "Cushion 41", "Cushions"),
        new FurnitureRecord("cushion-cushion42", "Cushion 42", "Cushions"),
        new FurnitureRecord("cushion-cushion43", "Cushion 43", "Cushions"),
        new FurnitureRecord("cushion-cushion44", "Cushion 44", "Cushions"),
        new FurnitureRecord("cushion-cushion45", "Cushion 45", "Cushions"),
        new FurnitureRecord("cushion-cushion46", "Cushion 46", "Cushions"),
        new FurnitureRecord("cushion-cushion47", "Cushion 47", "Cushions"),
        new FurnitureRecord("cushion-cushion48", "Cushion 48", "Cushions"),
        new FurnitureRecord("cushion-cushion49", "Cushion 49", "Cushions"),
        new FurnitureRecord("cushion-cushion50", "Cushion 50", "Cushions"),
        new FurnitureRecord("drawer-drawer01", "Drawer 01", "Drawers"),
        new FurnitureRecord("drawer-drawer02", "Drawer 02", "Drawers"),
        new FurnitureRecord("drawer-drawer03", "Drawer 03", "Drawers"),
        new FurnitureRecord("drawer-drawer04", "Drawer 04", "Drawers"),
        new FurnitureRecord("drawer-drawer05", "Drawer 05", "Drawers"),
        new FurnitureRecord("drawer-drawer06", "Drawer 06", "Drawers"),
        new FurnitureRecord("drawer-drawer07", "Drawer 07", "Drawers"),
        new FurnitureRecord("drawer-drawer08", "Drawer 08", "Drawers"),
        new FurnitureRecord("drawer-drawer09", "Drawer 09", "Drawers"),
        new FurnitureRecord("drawer-drawer10", "Drawer 10", "Drawers"),
        new FurnitureRecord("drawer-drawer11", "Drawer 11", "Drawers"),
        new FurnitureRecord("drawer-drawer12", "Drawer 12", "Drawers"),
        new FurnitureRecord("drawer-drawer13", "Drawer 13", "Drawers"),
        new FurnitureRecord("drawer-drawer14", "Drawer 14", "Drawers"),
        new FurnitureRecord("drawer-drawer15", "Drawer 15", "Drawers"),
        new FurnitureRecord("drawer-drawer16", "Drawer 16", "Drawers"),
        new FurnitureRecord("drawer-drawer17", "Drawer 17", "Drawers"),
        new FurnitureRecord("drawer-drawer18", "Drawer 18", "Drawers"),
        new FurnitureRecord("drawer-drawer19", "Drawer 19", "Drawers"),
        new FurnitureRecord("drawer-drawer20", "Drawer 20", "Drawers"),
        new FurnitureRecord("drawer-drawer21", "Drawer 21", "Drawers"),
        new FurnitureRecord("drawer-drawer22", "Drawer 22", "Drawers"),
        new FurnitureRecord("drawer-drawer23", "Drawer 23", "Drawers"),
        new FurnitureRecord("drawer-drawer24", "Drawer 24", "Drawers"),
        new FurnitureRecord("drawer-drawer25", "Drawer 25", "Drawers"),
        new FurnitureRecord("drawer-drawer26", "Drawer 26", "Drawers"),
        new FurnitureRecord("drawer-drawer27", "Drawer 27", "Drawers"),
        new FurnitureRecord("drawer-drawer28", "Drawer 28", "Drawers"),
        new FurnitureRecord("drawer-drawer29", "Drawer 29", "Drawers"),
        new FurnitureRecord("drawer-drawer30", "Drawer 30", "Drawers"),
        new FurnitureRecord("drawer-drawer31", "Drawer 31", "Drawers"),
        new FurnitureRecord("drawer-drawer32", "Drawer 32", "Drawers"),
        new FurnitureRecord("drawer-drawer33", "Drawer 33", "Drawers"),
        new FurnitureRecord("drawer-drawer34", "Drawer 34", "Drawers"),
        new FurnitureRecord("drawer-drawer35", "Drawer 35", "Drawers"),
        new FurnitureRecord("drawer-drawer36", "Drawer 36", "Drawers"),
        new FurnitureRecord("drawer-drawer37", "Drawer 37", "Drawers"),
        new FurnitureRecord("drawer-drawer38", "Drawer 38", "Drawers"),
        new FurnitureRecord("drawer-drawer39", "Drawer 39", "Drawers"),
        new FurnitureRecord("drawer-drawer40", "Drawer 40", "Drawers"),
        new FurnitureRecord("drawer-drawer41", "Drawer 41", "Drawers"),
        new FurnitureRecord("drawer-drawer42", "Drawer 42", "Drawers"),
        new FurnitureRecord("drawer-drawer43", "Drawer 43", "Drawers"),
        new FurnitureRecord("drawer-drawer44", "Drawer 44", "Drawers"),
        new FurnitureRecord("drawer-drawer45", "Drawer 45", "Drawers"),
        new FurnitureRecord("drawer-drawer46", "Drawer 46", "Drawers"),
        new FurnitureRecord("drawer-drawer47", "Drawer 47", "Drawers"),
        new FurnitureRecord("drawer-drawer48", "Drawer 48", "Drawers"),
        new FurnitureRecord("drawer-drawer49", "Drawer 49", "Drawers"),
        new FurnitureRecord("drawer-drawer50", "Drawer 50", "Drawers"),
        new FurnitureRecord("kitchen-cabineta-sink", "Cabinet A Sink", "Kitchen"),
        new FurnitureRecord("kitchen-cabineta01", "Cabinet A 01", "Kitchen"),
        new FurnitureRecord("kitchen-cabineta02", "Cabinet A 02", "Kitchen"),
        new FurnitureRecord("kitchen-cabineta03", "Cabinet A 03", "Kitchen"),
        new FurnitureRecord("kitchen-cabineta04", "Cabinet A 04", "Kitchen"),
        new FurnitureRecord("kitchen-cabineta05", "Cabinet A 05", "Kitchen"),
        new FurnitureRecord("kitchen-cabineta06", "Cabinet A 06", "Kitchen"),
        new FurnitureRecord("kitchen-cabineta07", "Cabinet A 07", "Kitchen"),
        new FurnitureRecord("kitchen-cabinetacorner01", "Cabinet ACorner 01", "Kitchen"),
        new FurnitureRecord("kitchen-cabinetacorner02", "Cabinet ACorner 02", "Kitchen"),
        new FurnitureRecord("kitchen-cabinetb-sink", "Cabinet B Sink", "Kitchen"),
        new FurnitureRecord("kitchen-cabinetb01", "Cabinet B 01", "Kitchen"),
        new FurnitureRecord("kitchen-cabinetb02", "Cabinet B 02", "Kitchen"),
        new FurnitureRecord("kitchen-cabinetb03", "Cabinet B 03", "Kitchen"),
        new FurnitureRecord("kitchen-cabinetb04", "Cabinet B 04", "Kitchen"),
        new FurnitureRecord("kitchen-cabinetb05", "Cabinet B 05", "Kitchen"),
        new FurnitureRecord("kitchen-cabinetb06", "Cabinet B 06", "Kitchen"),
        new FurnitureRecord("kitchen-cabinetb07", "Cabinet B 07", "Kitchen"),
        new FurnitureRecord("kitchen-cabinetbcorner01", "Cabinet BCorner 01", "Kitchen"),
        new FurnitureRecord("kitchen-cabinetbcorner02", "Cabinet BCorner 02", "Kitchen"),
        new FurnitureRecord("kitchen-cabinetc-sink", "Cabinet C Sink", "Kitchen"),
        new FurnitureRecord("kitchen-cabinetc01", "Cabinet C 01", "Kitchen"),
        new FurnitureRecord("kitchen-cabinetc02", "Cabinet C 02", "Kitchen"),
        new FurnitureRecord("kitchen-cabinetc03", "Cabinet C 03", "Kitchen"),
        new FurnitureRecord("kitchen-cabinetc04", "Cabinet C 04", "Kitchen"),
        new FurnitureRecord("kitchen-cabinetc05", "Cabinet C 05", "Kitchen"),
        new FurnitureRecord("kitchen-cabinetc06", "Cabinet C 06", "Kitchen"),
        new FurnitureRecord("kitchen-cabinetc07", "Cabinet C 07", "Kitchen"),
        new FurnitureRecord("kitchen-cabinetccorner01", "Cabinet CCorner 01", "Kitchen"),
        new FurnitureRecord("kitchen-cabinetccorner02", "Cabinet CCorner 02", "Kitchen"),
        new FurnitureRecord("kitchen-cabinetd-sink", "Cabinet D Sink", "Kitchen"),
        new FurnitureRecord("kitchen-cabinetd01", "Cabinet D 01", "Kitchen"),
        new FurnitureRecord("kitchen-cabinetd02", "Cabinet D 02", "Kitchen"),
        new FurnitureRecord("kitchen-cabinetd03", "Cabinet D 03", "Kitchen"),
        new FurnitureRecord("kitchen-cabinetd04", "Cabinet D 04", "Kitchen"),
        new FurnitureRecord("kitchen-cabinetd05", "Cabinet D 05", "Kitchen"),
        new FurnitureRecord("kitchen-cabinetd06", "Cabinet D 06", "Kitchen"),
        new FurnitureRecord("kitchen-cabinetd07", "Cabinet D 07", "Kitchen"),
        new FurnitureRecord("kitchen-cabinetdcorner01", "Cabinet DCorner 01", "Kitchen"),
        new FurnitureRecord("kitchen-cabinetdcorner02", "Cabinet DCorner 02", "Kitchen"),
        new FurnitureRecord("kitchen-cabinete-sink", "Cabinet E Sink", "Kitchen"),
        new FurnitureRecord("kitchen-cabinete01", "Cabinet E 01", "Kitchen"),
        new FurnitureRecord("kitchen-cabinete02", "Cabinet E 02", "Kitchen"),
        new FurnitureRecord("kitchen-cabinete03", "Cabinet E 03", "Kitchen"),
        new FurnitureRecord("kitchen-cabinete04", "Cabinet E 04", "Kitchen"),
        new FurnitureRecord("kitchen-cabinete05", "Cabinet E 05", "Kitchen"),
        new FurnitureRecord("kitchen-cabinete06", "Cabinet E 06", "Kitchen"),
        new FurnitureRecord("kitchen-cabinete07", "Cabinet E 07", "Kitchen"),
        new FurnitureRecord("kitchen-cabinetecorner01", "Cabinet ECorner 01", "Kitchen"),
        new FurnitureRecord("kitchen-cabinetecorner02", "Cabinet ECorner 02", "Kitchen"),
        new FurnitureRecord("kitchen-cabinetf-sink", "Cabinet F Sink", "Kitchen"),
        new FurnitureRecord("kitchen-cabinetf01", "Cabinet F 01", "Kitchen"),
        new FurnitureRecord("kitchen-cabinetf02", "Cabinet F 02", "Kitchen"),
        new FurnitureRecord("kitchen-cabinetf03", "Cabinet F 03", "Kitchen"),
        new FurnitureRecord("kitchen-cabinetf04", "Cabinet F 04", "Kitchen"),
        new FurnitureRecord("kitchen-cabinetf05", "Cabinet F 05", "Kitchen"),
        new FurnitureRecord("kitchen-cabinetf06", "Cabinet F 06", "Kitchen"),
        new FurnitureRecord("kitchen-cabinetf07", "Cabinet F 07", "Kitchen"),
        new FurnitureRecord("kitchen-cabinetfcorner01", "Cabinet FCorner 01", "Kitchen"),
        new FurnitureRecord("kitchen-cabinetfcorner02", "Cabinet FCorner 02", "Kitchen"),
        new FurnitureRecord("kitchen-cabinetg-sink", "Cabinet G Sink", "Kitchen"),
        new FurnitureRecord("kitchen-cabinetg01", "Cabinet G 01", "Kitchen"),
        new FurnitureRecord("kitchen-cabinetg02", "Cabinet G 02", "Kitchen"),
        new FurnitureRecord("kitchen-cabinetg03", "Cabinet G 03", "Kitchen"),
        new FurnitureRecord("kitchen-cabinetg04", "Cabinet G 04", "Kitchen"),
        new FurnitureRecord("kitchen-cabinetg05", "Cabinet G 05", "Kitchen"),
        new FurnitureRecord("kitchen-cabinetg06", "Cabinet G 06", "Kitchen"),
        new FurnitureRecord("kitchen-cabinetg07", "Cabinet G 07", "Kitchen"),
        new FurnitureRecord("kitchen-cabinetgcorner01", "Cabinet GCorner 01", "Kitchen"),
        new FurnitureRecord("kitchen-cabinetgcorner02", "Cabinet GCorner 02", "Kitchen"),
        new FurnitureRecord("kitchen-gasstove01", "Gas Stove 01", "Kitchen"),
        new FurnitureRecord("kitchen-gasstove02", "Gas Stove 02", "Kitchen"),
        new FurnitureRecord("kitchen-gasstove03", "Gas Stove 03", "Kitchen"),
        new FurnitureRecord("kitchen-gasstove04", "Gas Stove 04", "Kitchen"),
        new FurnitureRecord("kitchen-gasstove05", "Gas Stove 05", "Kitchen"),
        new FurnitureRecord("kitchen-gasstove06", "Gas Stove 06", "Kitchen"),
        new FurnitureRecord("kitchen-gasstove07", "Gas Stove 07", "Kitchen"),
        new FurnitureRecord("kitchen-kitchenexhaust01", "Kitchen Exhaust 01", "Kitchen"),
        new FurnitureRecord("kitchen-kitchenexhaust02", "Kitchen Exhaust 02", "Kitchen"),
        new FurnitureRecord("kitchen-kitchenexhaust03", "Kitchen Exhaust 03", "Kitchen"),
        new FurnitureRecord("kitchen-kitchenexhaust04", "Kitchen Exhaust 04", "Kitchen"),
        new FurnitureRecord("kitchen-kitchenexhaust05", "Kitchen Exhaust 05", "Kitchen"),
        new FurnitureRecord("kitchen-kitchenexhaust06", "Kitchen Exhaust 06", "Kitchen"),
        new FurnitureRecord("kitchen-kitchenexhaust07", "Kitchen Exhaust 07", "Kitchen"),
        new FurnitureRecord("kitchen-kitchenoven01", "Kitchen Oven 01", "Kitchen"),
        new FurnitureRecord("kitchen-kitchenoven02", "Kitchen Oven 02", "Kitchen"),
        new FurnitureRecord("kitchen-kitchenoven03", "Kitchen Oven 03", "Kitchen"),
        new FurnitureRecord("kitchen-kitchenoven04", "Kitchen Oven 04", "Kitchen"),
        new FurnitureRecord("kitchen-kitchenoven05", "Kitchen Oven 05", "Kitchen"),
        new FurnitureRecord("kitchen-kitchenoven06", "Kitchen Oven 06", "Kitchen"),
        new FurnitureRecord("kitchen-kitchenoven07", "Kitchen Oven 07", "Kitchen"),
        new FurnitureRecord("kitchen-microwaveoven01", "Microwave Oven 01", "Kitchen"),
        new FurnitureRecord("kitchen-microwaveoven02", "Microwave Oven 02", "Kitchen"),
        new FurnitureRecord("kitchen-microwaveoven03", "Microwave Oven 03", "Kitchen"),
        new FurnitureRecord("kitchen-microwaveoven04", "Microwave Oven 04", "Kitchen"),
        new FurnitureRecord("kitchen-microwaveoven05", "Microwave Oven 05", "Kitchen"),
        new FurnitureRecord("kitchen-microwaveoven06", "Microwave Oven 06", "Kitchen"),
        new FurnitureRecord("kitchen-microwaveoven07", "Microwave Oven 07", "Kitchen"),
        new FurnitureRecord("kitchen-refrigerator01", "Refrigerator 01", "Kitchen"),
        new FurnitureRecord("kitchen-refrigerator02", "Refrigerator 02", "Kitchen"),
        new FurnitureRecord("kitchen-refrigerator03", "Refrigerator 03", "Kitchen"),
        new FurnitureRecord("kitchen-refrigerator04", "Refrigerator 04", "Kitchen"),
        new FurnitureRecord("kitchen-refrigerator05", "Refrigerator 05", "Kitchen"),
        new FurnitureRecord("kitchen-refrigerator06", "Refrigerator 06", "Kitchen"),
        new FurnitureRecord("kitchen-refrigerator07", "Refrigerator 07", "Kitchen"),
        new FurnitureRecord("kitchen-sink01", "Sink 01", "Kitchen"),
        new FurnitureRecord("kitchen-sink02", "Sink 02", "Kitchen"),
        new FurnitureRecord("kitchen-sink03", "Sink 03", "Kitchen"),
        new FurnitureRecord("kitchen-sink04", "Sink 04", "Kitchen"),
        new FurnitureRecord("kitchen-sink05", "Sink 05", "Kitchen"),
        new FurnitureRecord("kitchen-sink06", "Sink 06", "Kitchen"),
        new FurnitureRecord("kitchen-sink07", "Sink 07", "Kitchen"),
        new FurnitureRecord("sofa-sofa01", "Sofa 01", "Sofas"),
        new FurnitureRecord("sofa-sofa02", "Sofa 02", "Sofas"),
        new FurnitureRecord("sofa-sofa03", "Sofa 03", "Sofas"),
        new FurnitureRecord("sofa-sofa04", "Sofa 04", "Sofas"),
        new FurnitureRecord("sofa-sofa05", "Sofa 05", "Sofas"),
        new FurnitureRecord("sofa-sofa06", "Sofa 06", "Sofas"),
        new FurnitureRecord("sofa-sofa07", "Sofa 07", "Sofas"),
        new FurnitureRecord("sofa-sofa08", "Sofa 08", "Sofas"),
        new FurnitureRecord("sofa-sofa09", "Sofa 09", "Sofas"),
        new FurnitureRecord("sofa-sofa10", "Sofa 10", "Sofas"),
        new FurnitureRecord("sofa-sofa11", "Sofa 11", "Sofas"),
        new FurnitureRecord("sofa-sofa12", "Sofa 12", "Sofas"),
        new FurnitureRecord("sofa-sofa13", "Sofa 13", "Sofas"),
        new FurnitureRecord("sofa-sofa14", "Sofa 14", "Sofas"),
        new FurnitureRecord("sofa-sofa15", "Sofa 15", "Sofas"),
        new FurnitureRecord("sofa-sofa16", "Sofa 16", "Sofas"),
        new FurnitureRecord("sofa-sofa17", "Sofa 17", "Sofas"),
        new FurnitureRecord("sofa-sofa18", "Sofa 18", "Sofas"),
        new FurnitureRecord("sofa-sofa19", "Sofa 19", "Sofas"),
        new FurnitureRecord("sofa-sofa20", "Sofa 20", "Sofas"),
        new FurnitureRecord("sofa-sofa21", "Sofa 21", "Sofas"),
        new FurnitureRecord("sofa-sofa22", "Sofa 22", "Sofas"),
        new FurnitureRecord("sofa-sofa23", "Sofa 23", "Sofas"),
        new FurnitureRecord("sofa-sofa24", "Sofa 24", "Sofas"),
        new FurnitureRecord("sofa-sofa25", "Sofa 25", "Sofas"),
        new FurnitureRecord("sofa-sofa26", "Sofa 26", "Sofas"),
        new FurnitureRecord("sofa-sofa27", "Sofa 27", "Sofas"),
        new FurnitureRecord("sofa-sofa28", "Sofa 28", "Sofas"),
        new FurnitureRecord("sofa-sofa29", "Sofa 29", "Sofas"),
        new FurnitureRecord("sofa-sofa30", "Sofa 30", "Sofas"),
        new FurnitureRecord("sofa-sofa31", "Sofa 31", "Sofas"),
        new FurnitureRecord("sofa-sofa32", "Sofa 32", "Sofas"),
        new FurnitureRecord("sofa-sofa33", "Sofa 33", "Sofas"),
        new FurnitureRecord("sofa-sofa34", "Sofa 34", "Sofas"),
        new FurnitureRecord("sofa-sofa35", "Sofa 35", "Sofas"),
        new FurnitureRecord("sofa-sofa36", "Sofa 36", "Sofas"),
        new FurnitureRecord("sofa-sofa37", "Sofa 37", "Sofas"),
        new FurnitureRecord("sofa-sofa38", "Sofa 38", "Sofas"),
        new FurnitureRecord("sofa-sofa39", "Sofa 39", "Sofas"),
        new FurnitureRecord("sofa-sofa40", "Sofa 40", "Sofas"),
        new FurnitureRecord("sofa-sofa41", "Sofa 41", "Sofas"),
        new FurnitureRecord("sofa-sofa42", "Sofa 42", "Sofas"),
        new FurnitureRecord("sofa-sofa43", "Sofa 43", "Sofas"),
        new FurnitureRecord("sofa-sofa44", "Sofa 44", "Sofas"),
        new FurnitureRecord("sofa-sofa45", "Sofa 45", "Sofas"),
        new FurnitureRecord("sofa-sofa46", "Sofa 46", "Sofas"),
        new FurnitureRecord("sofa-sofa47", "Sofa 47", "Sofas"),
        new FurnitureRecord("sofa-sofa48", "Sofa 48", "Sofas"),
        new FurnitureRecord("sofa-sofa49", "Sofa 49", "Sofas"),
        new FurnitureRecord("sofa-sofa50", "Sofa 50", "Sofas"),
        new FurnitureRecord("table-table01", "Table 01", "Tables"),
        new FurnitureRecord("table-table02", "Table 02", "Tables"),
        new FurnitureRecord("table-table03", "Table 03", "Tables"),
        new FurnitureRecord("table-table04", "Table 04", "Tables"),
        new FurnitureRecord("table-table05", "Table 05", "Tables"),
        new FurnitureRecord("table-table06", "Table 06", "Tables"),
        new FurnitureRecord("table-table07", "Table 07", "Tables"),
        new FurnitureRecord("table-table08", "Table 08", "Tables"),
        new FurnitureRecord("table-table09", "Table 09", "Tables"),
        new FurnitureRecord("table-table10", "Table 10", "Tables"),
        new FurnitureRecord("table-table11", "Table 11", "Tables"),
        new FurnitureRecord("table-table12", "Table 12", "Tables"),
        new FurnitureRecord("table-table13", "Table 13", "Tables"),
        new FurnitureRecord("table-table14", "Table 14", "Tables"),
        new FurnitureRecord("table-table15", "Table 15", "Tables"),
        new FurnitureRecord("table-table16", "Table 16", "Tables"),
        new FurnitureRecord("table-table17", "Table 17", "Tables"),
        new FurnitureRecord("table-table18", "Table 18", "Tables"),
        new FurnitureRecord("table-table19", "Table 19", "Tables"),
        new FurnitureRecord("table-table20", "Table 20", "Tables"),
        new FurnitureRecord("table-table21", "Table 21", "Tables"),
        new FurnitureRecord("table-table22", "Table 22", "Tables"),
        new FurnitureRecord("table-table23", "Table 23", "Tables"),
        new FurnitureRecord("table-table24", "Table 24", "Tables"),
        new FurnitureRecord("table-table25", "Table 25", "Tables"),
        new FurnitureRecord("table-table26", "Table 26", "Tables"),
        new FurnitureRecord("table-table27", "Table 27", "Tables"),
        new FurnitureRecord("table-table28", "Table 28", "Tables"),
        new FurnitureRecord("table-table29", "Table 29", "Tables"),
        new FurnitureRecord("table-table30", "Table 30", "Tables"),
        new FurnitureRecord("table-table31", "Table 31", "Tables"),
        new FurnitureRecord("table-table32", "Table 32", "Tables"),
        new FurnitureRecord("table-table33", "Table 33", "Tables"),
        new FurnitureRecord("table-table34", "Table 34", "Tables"),
        new FurnitureRecord("table-table35", "Table 35", "Tables"),
        new FurnitureRecord("table-table36", "Table 36", "Tables"),
        new FurnitureRecord("table-table37", "Table 37", "Tables"),
        new FurnitureRecord("table-table38", "Table 38", "Tables"),
        new FurnitureRecord("table-table39", "Table 39", "Tables"),
        new FurnitureRecord("table-table40", "Table 40", "Tables"),
        new FurnitureRecord("table-table41", "Table 41", "Tables"),
        new FurnitureRecord("table-table42", "Table 42", "Tables"),
        new FurnitureRecord("table-table43", "Table 43", "Tables"),
        new FurnitureRecord("table-table44", "Table 44", "Tables"),
        new FurnitureRecord("table-table45", "Table 45", "Tables"),
        new FurnitureRecord("table-table46", "Table 46", "Tables"),
        new FurnitureRecord("table-table47", "Table 47", "Tables"),
        new FurnitureRecord("table-table48", "Table 48", "Tables"),
        new FurnitureRecord("table-table49", "Table 49", "Tables"),
        new FurnitureRecord("table-table50", "Table 50", "Tables"),
    };

    public static IReadOnlyList<FurnitureRecord> Items => CatalogItems;

    public static string[] Categories =>
        new[] { "All", "Chairs", "Sofas", "Tables", "Beds", "Closets", "Drawers", "Kitchen", "Bathroom", "Cushions" };

    public static FurnitureRecord Find(string id)
    {
        return CatalogItems.Find(item => item.Id == id) ?? CatalogItems[0];
    }

    public static string GetImportedPackSummary()
    {
        var path = Path.Combine(Application.dataPath, "Furniture Mega Pack", "Prefabs");
        if (!Directory.Exists(path))
            return "Furniture pack not found.";

        var count = Directory.GetFiles(path, "*.prefab", SearchOption.AllDirectories).Length;
        return $"{count} imported prefabs found";
    }
}
